"""Add tx_hash field to transactions table

Revision ID: 71c30d32e708
Revises: add_nonces_table
Create Date: 2025-11-01 21:25:16.326417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71c30d32e708'
down_revision = 'add_nonces_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tx_hash', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_dapp_transactions_tx_hash'), ['tx_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dapp_transactions_tx_hash'))
        batch_op.drop_column('tx_hash')

    # ### end Alembic commands ###
