"""empty message

Revision ID: 7af6b0138b5a
Revises: 
Create Date: 2025-10-28 12:32:21.102366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af6b0138b5a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reference', sa.String(length=255), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('incoming_currency', sa.String(length=10), nullable=False),
    sa.Column('outgoing_currency', sa.String(length=10), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('payer_id', sa.String(length=255), nullable=True),
    sa.Column('payee_id', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('wallet_address', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('instruction_type', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('queue_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='dapp'
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solana_transactions_external_reference'), ['external_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_solana_transactions_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_solana_transactions_payee_id'), ['payee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solana_transactions_payer_id'), ['payer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_solana_transactions_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_solana_transactions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_solana_transactions_wallet_address'), ['wallet_address'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solana_transactions_wallet_address'))
        batch_op.drop_index(batch_op.f('ix_solana_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_solana_transactions_reference'))
        batch_op.drop_index(batch_op.f('ix_solana_transactions_payer_id'))
        batch_op.drop_index(batch_op.f('ix_solana_transactions_payee_id'))
        batch_op.drop_index(batch_op.f('ix_solana_transactions_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_solana_transactions_external_reference'))

    op.drop_table('transactions', schema='dapp')
    # ### end Alembic commands ###
